name: "astral_cord"

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Compile rust code
      env:
        NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz"
      run: |
        cd ./astral_cord
        nix-build ./astral_cord_bin.nix

