name: "astral_cord"

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v17
    - name: Compile rust code
      run: |
        nix-build default.nix -A astral_cord
