name: "crystal_ball"

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Compile code into javascript bundle
      env:
        NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz"
      run: |
        cd ./crystal_ball
        nix-shell --pure --run 'bazel build --sandbox_debug --verbose_failures :bundle'
